var zoomExpr = require('../lib/expr.js')
var test = require('tape')

test('zoomExpr', function (t) {
  t.ok(zoomExpr('zoom<9', { zoom: 6 }), '<')
  t.ok(zoomExpr('zoom>5', { zoom: 7 }), '>')
  t.ok(zoomExpr('zoom>=4', { zoom: 5 }), '>=')
  t.ok(zoomExpr('x <= 6', { x: 2 }), '<=')
  t.ok(zoomExpr('zoom=11', { zoom: 11 }), '=')
  t.ok(zoomExpr('zoom==12', { zoom: 12 }), '==')
  t.ok(zoomExpr('zoom===10', { zoom: 10 }), '===')
  t.ok(zoomExpr('x <= 8.0', { x: 8 }), 'float condition')
  t.ok(zoomExpr('x >= 7', { x: 9.5 }), 'float input')
  t.ok(zoomExpr('x >= 5.0', { x: 11.5 }), 'float condition and float input')
  t.ok(zoomExpr('11 > zoom >= 3', { zoom: 8 }), '2 comparisons')
  t.ok(zoomExpr('11 <= zoom = 13', { zoom: 13 }), '2 comparisons')
  t.ok(zoomExpr('4 < zoom && 5 < zoom <= 10', { zoom: 9 }), '2 comparisons and boolean')
  t.notOk(zoomExpr('zoom>=10&&zoom<=14', { zoom: 8 }), 'no spaces, && boolean')
  t.notOk(zoomExpr('zoom=10||15>zoom', { zoom: 18 }), 'no spaces, || boolean')
  t.notOk(zoomExpr('zoom>=x', { zoom: 5, x: 10 }), '2 variable comparison')
  t.notOk(zoomExpr('3 > zoom || 6 < zoom <= 11 || zoom == 14', { zoom: 12 }), '3 comparisons, 2 booleans')
  t.ok(zoomExpr('night = x || zoom == 5', { night: true, x: true, zoom: 5 }), 'boolean input')
  t.ok(zoomExpr('x || zoom == 5', { x: true, zoom: 5 }), 'boolean input')
  t.ok(zoomExpr('night === x && 15 < zoom <= 21', { night: false, x: false, zoom: 17 }), 'boolean input')
  t.throws(function () { zoomExpr('zoom =< 10', { zoom: 3 }) }, '=< not accepted')
  t.throws(function () { zoomExpr('zoom => 10', { zoom: 15 }) }, '=> not accepted')
  t.throws(function () { zoomExpr('zoom=10??15>zoom', { zoom: 20 }) }, 'question marks not accepted')
  t.throws(function () { zoomExpr('zoom:10', { zoom: 17 }) }, 'colon not accepted')
  t.throws(function () { zoomExpr('zoom=[10-14]', { zoom: 19 }) }, 'interval specified incorrectly')
  t.throws(function () { zoomExpr('zoom={7-11}', { zoom: 8 }) }, 'interval specified incorrectly')
  t.throws(function () { zoomExpr('zoom=10;15>zoom', { zoom: 16 }) }, 'semicolon not accepted')
  t.throws(function () { zoomExpr('x<10 ? 5 : 7', { x: 8 }) }, 'ternary expressions not accepted')
  t.throws(function () { zoomExpr('night <= 10', { }) }, 'undefined variable')

  t.end()
})
